//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeMos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string KategoriAdi { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Miktar { get; set; }
        public Nullable<int> Stok { get; set; }
        public string TedarikciAdi { get; set; }
        public Nullable<decimal> SatisFiyati { get; set; }
        public Nullable<decimal> AlisFiyati { get; set; }
        public Nullable<int> StokCikisi { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
